### ISSUE TITLE
再补充几个，感觉这种是永远拉黑不完的

### ISSUE THREAD

**Issue by RWDai** [gitsang/zhihu-block#1]
https://www.zhihu.com/org/zhi-yun-dong-43 知乎运动
https://www.zhihu.com/org/zhi-hu-kao-yan 考研研习社
https://www.zhihu.com/org/chao-zan-bao-xiao-zhu-shou 超赞包小助手
https://www.zhihu.com/org/zhi-hu-mei-shi-96 知乎美食
https://www.zhihu.com/org/she-ji-yan-jiu-yuan-80 AI盐究院

**Comment by gitsang** [comment]
感谢贡献！

> 只能是有一个拉黑一个了
